olix0r/kubert

- kubert/Cargo.toml
- kubert/src/client.rs
Replace the `kube` dependency with `kube-client`, which is used only by
the `client` feature.
Update Cargo.toml to express patch versions, since compilation failed on
minimal versions.
> Simplify dependencies

- kubert/src/server.rs
Ensure that credentials can be loaded before binding the server.
> Split server into smaller functions

- .github/workflows/lints.yml
- kubert/src/client.rs
- kubert/src/lib.rs
- kubert/src/log.rs
- kubert/src/server.rs
- kubert/src/shutdown.rs
Also add `--cluster` and `--user` flags to the `ClientArgs` for
completeness.
This change adds a lint check to ensure docs are valid, too.
> Add docs for all public types

- README.md
- kubert/src/client.rs
This change replicates the behavior of `kube::Client::try_default` so
in-cluster configs are tried when a kubeconfig can not be found. The
fallback is only attempted when CLI flags do not configure kubeconfig
parameters.
> client: Fallback to using the in-cluster config

- .github/workflows/lint.yml
- .github/workflows/test.yml
- deny.toml
- kubert/Cargo.toml
- kubert/src/lib.rs
- kubert/src/requeue.rs
As a controller processes events, it may not be able to act successfully
on these events: there may be a transient problem when writing to the
API server, or the system may not be in a converged state and it may be
necessary to reprocess the update at a later time.
The `requeue` channel provides a bounded, multi-producer/single-
consumer, delay-queue channel. Applications can use this channel to
reschedule updates for a later time. While this is especially useful for
controllers, this channel is not inherently tied to Kubernetes in any
way.
> Add a requeue channel

- kubert/Cargo.toml
- kubert/src/admin.rs
- kubert/src/client.rs
- kubert/src/lib.rs
- kubert/src/log.rs
- kubert/src/server.rs
- kubert/src/shutdown.rs
Controllers need an HTTP admin server for Kubernetes liveness and
readiness probes.
This change adds an `admin` module that configures a server with
`/ready` and `/live` endpoints.
> Add an admin server utility

- kubert/Cargo.toml
- kubert/src/server.rs
Currently the server only attempts to parse RSA private keys. This
change updates the server to first attempt to read PKSC8 private keys
before attempting to parse the key file as RSA.
> server: Read PKSC8 private keys

- kubert/src/shutdown.rs
`shutdown::CancelOnShutdown` wraps a `Future` or `Stream` so that the
task completes when shutdown is signaled. Currently, this is done by
stopping all additional work on these tasks as soon as the shutdown
signal is observed. This makes it difficult to ensure that in-flight
work is processed during shutdown.
This change alters the behavior so that `CancelOnShutdown` polls the
inner `Future` or `Stream` before polling the shutdown watch, so that
the shutdown watch is only polled when the inner instance is pending.
This will, in-turn, block the shutdown and runtime futures from
completing until all pending work is processed.
In pathological cases, this could prevent the process from terminating
gracefully. It seems better to the user or kubelet abort the application
if it doesn't complete …
> shutdown: Bias towards processing remaining work

- .github/workflows/test.yml
- Cargo.toml
- README.md
- deny.toml
- examples/Cargo.toml
- examples/README.md
- examples/watch_pods.rs
This change adds a simple `watch-pods` example that uses
`kubert::Runtime` to build a simple application that logs pod updates.
Closes #11
> Add a simple example

- kubert/Cargo.toml
- kubert/src/runtime.rs
- kubert/src/server.rs
It's not easy to know whether the server is listening, accepting
connections, etc.
This change adds some debug logging to the `server` and updates
`Runtime` to include `server_addr` accessors.
> server: Add diganostic logging

- kubert/src/client.rs
Adds support for the `--kubeconfig` flag to specify the path to a kubeconfig file to use.
Adds support for the `--as` and `--as-group` to support impersonation or a user or group.
Signed-off-by: Alex Leong <alex@buoyant.io>
> Add support for kubeconfig and impersonation flags

- kubert/src/client.rs
Followup to #21
Allow the kubeconfig loading logic to also consider `$HOME/.kube/config`
> Improve kubeconfig loading logic

- .dockerignore
- .github/workflows/client.yml
- .github/workflows/features.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- deny.toml
- examples/Cargo.toml
- examples/Dockerfile
- examples/watch_pods.rs
The client initialization logic isn't tested in this repo.
This change adds a `client` CI workflow that tests that the `watch-pods`
example runs both from within the cluster and from an external client.
It also pins all rust versions to the MSRV (1.56.1).
> Add client integration tests

- README.md
- kubert/Cargo.toml
- kubert/src/index.rs
- kubert/src/lib.rs
When watching Kubernetes resources and keeping a data structure up-to
date, there's a fairly straightforward pattern for keeping a
data-structure up-to-date.
This change adds a `index` module that drive the main event-looping
logic, locking a data structure, and applying updates, ensuring that the
data structure observes implicit removing following a stream restart.
> Add an `index` utility

- deny.toml
- examples/Cargo.toml
- kubert/Cargo.toml
- kubert/src/index.rs
Rather than force the indexing type to keep track of its own key
structures, it's better for the indexer to do this internaly. This makes
it so that the hash implementation isn't a part of the public interface;
and also makes it so that the index implementation need not track all
resources for proper operations.
This is a breaing change that removes the `snapshot_keys` method from
the `IndexClusterResource` and `IndexNamespacedResource` traits. As
such, the crate version is bumped to v0.4.0
> Change `index` to keep track of its keys

- kubert/Cargo.toml
- kubert/src/index.rs
Indexers may want to handle batch updates specially, for instance to
run an expensive computation after the batch update is applied. With the
current `Index` trait APIs, this is not possible.
This change adds `IndexClusterResources::reset` and
`IndexNamespacedResources::reset` methods with a default implementation
that preserves the current behavior: `apply` is called for each live
resource and `delete` is called for all resources that aren't included
in the update. This default trait-method implementation ensures this
change is backwards-compatible.
> index: Allow indexers to handle restarts

- .github/workflows/features.yml
This replaces use of `cargo-hack` with a build matrix that compiles each
feature independently.
Signed-off-by: Oliver Gould <ver@buoyant.io>
> ci: Parallelize per-feature checks

- examples/Cargo.toml
- examples/watch_pods.rs
- kubert/Cargo.toml
- kubert/src/index.rs
kube v0.74 deprecates `ResourceExt::name`. We replace our uses with
`ResourceExt::name_unchecked`, as we are handling resources from the API
server (and so a name must be set).
> Update to kube v0.74

- kubert/src/admin.rs
- kubert/src/server.rs
The admin server sets a 2s request header timeout to prevent clients
from holding connections open indefinitely. No such timeout is
configured on the admission controller server. This change updates the
`server` module to apply a 2s request header timeout.
> server: Set a 2s request header timeout

- kubert/Cargo.toml
Currently, the docs.rs documentation for `kubert` doesn't show the `kubert::index` module, or any of its contents (such as the `Index{Cluster, Namespaced}Resource` traits).
For example, here's the current docs from https://docs.rs/kubert/0.10.0/kubert/index.html
This is because the crate's docs.rs metadata currently enables a specific list of features, which doesn't include the `index` feature. Presumably, the list of features to enable when building docs was not modified when the `index` module was added.
This commit fixes this by changing the docs.rs metadata so that `--all-features` is passed instead of a list of feature flags. This way, not only is the `index` module now present, but also, if any new feature flags are added, the docs.rs metadata won't need to be modified again.
Note …
> docs: fix `index` module not being present on docs.rs

- examples/Cargo.toml
- examples/watch_pods.rs
- kubert/Cargo.toml
- kubert/src/log.rs
Clap now requires that argument values are cloneable, which prevents us from using a `tracing_subcriber::EnvFilter` directly. The `LogFilter` type is changed to wrap a shareable heap-allocated `EnvFilter`.
This change bumps kubert's version to v0.11.0.
> Update to clap v4

- .github/workflows/client.yml
- .github/workflows/features.yml
- examples/Cargo.toml
- examples/lease.rs
- examples/tests/lease.rs
- justfile
- kubert/Cargo.toml
- kubert/src/lease.rs
- kubert/src/lib.rs
Applications that manage state in Kubernetes--for instance, those that update resource statuses--may need to coordinate access to that state so that only one replica is trying to update resources at a time.
The `lease` module manages coordination.k8s.io/v1 Lease resources to ensure that only a single claimant owns the lease.
> lease: A distributed, cooperative lock

- kubert/src/admin.rs
This is probably not actually a big deal, but according to [RFC 9110], when sending a 405 Method Not Allowed status:
> The origin server MUST generate an [Allow] header field in a 405
> response containing a list of the target resource's currently
> supported methods.
This branch updates the admin server's `/live` and `/ready` endpoints so that when an unsupported request method is received, the returned 405 response includes an `Allow` header, making the server compliant with the RFC.
[RFC 9110]: https://httpwg.org/specs/rfc9110.html#status.405
[Allow]: https://httpwg.org/specs/rfc9110.html#field.allow
> admin: make 405 responses standards-compliant

- .github/workflows/features.yml
- deny.toml
- kubert/Cargo.toml
- kubert/src/admin.rs
- kubert/src/admin/metrics.rs
This branch builds on PR #107 to add a production-ready Prometheus
metrics endpoint. As discussed in #107, the metrics endpoint is
implemented using the `metrics-endpoint-prometheus` and
`metrics-process` crates, and will serve process metrics by default. If
the application or other libraries use the `metrics` crate to emit their
own metrics, these metrics will be included in the Prometheus endpoint
as well.
Changes from #107 include the following:
- The metrics endpoint is feature-flagged behind the "metrics" feature.
- Metrics are compressed using GZIP when the request includes an
`accept-encoding: gzip` header
- The `PrometheusBuilder` type from `metrics-exporter-prometheus` is
wrapped in a newtype. This is because `metrics-exporter-prometheus`
includes functionality for configuring an …
> add Prometheus metrics endpoint

- examples/lease.rs
- kubert/src/lease.rs
Clippy emits a warning when an explicit dereference (`*`) is used for a deref coercion that would be performed automatically by the compiler. This branch fixes a few of those warnings.
> style: fix clippy auto-deref lints

- deny.toml
Our `cargo deny` checks are failing because `num_cpus` (a transitive dep of `metrics-util` and `tokio`) and `io-lifetimes` (a transitive dep of `metrics-process`) depend on incompatible versions of...whatever this crate is...
> chore: allow duplicate versions of `hermit-abi` and `bitflags`

- kubert/src/admin.rs
- kubert/src/runtime.rs
We update the runtime builder's `with_admin` function to accept a `impl Into<admin::Builder>` rather than a `AdminArgs`.  This gives callers the flexibility of providing their own `admin::Builder` if they need to customize it.
For example:
```
let mut admin = admin_args.into_builder();
admin.with_default_prometheus();
let mut runtime = kubert::Runtime::builder()
.with_log(log_level, log_format)
.with_admin(admin)
```
> Allow runtime to accept an admin builder

- kubert/Cargo.toml
- kubert/src/lease.rs
Currently, if the `ensure_claimed` call in the `LeaseManager::spawn`
background task fails, the entire task will bail and terminate
immediately. This is not desirable, as the intended use of
`LeaseManager::spawn` is to spawn a single background task that will
manage leasses for the entire lifetime of a controller process, and it
should not terminate in the face of a transient error claiming the
lease.
This branch changes `LeaseManager::spawn` to retry transient errors with
an exponential backoff strategy. Exponential backoffs are implemented
using the `backoff` crate, but --- because this dependency is not
exposed in the public API -- this is strictly an implementation detail,
and the dependency can be swapped out for another exponential backoff
implementation later, if desired. Errors …
> lease: retry errors claiming lease in `LeaseManager::spawn`

- deny.toml
This branch allows duplicate dependencies on the following crates:
* `indexmap`, because the versions of `serde_json` and `serde_yaml` currently pulled by our `kube-core` dependency require incompatible `indexmap` versions. We ignore `indexmap`'s whole dep tree, because the incompatible `indexmap` versions also depend on incompatible versions of `hashbrown`.
* `syn`, because the proc-macro ecosystem is still in the process of updating from `syn` v1 to `syn` v2.
This should fix the CI build.
> chore: allow some duplicate deps

- kubert/Cargo.toml
- kubert/src/client.rs
- kubert/src/runtime.rs
- kubert/src/server.rs
Currently, Kubert's `Runtime` will always construct a Kubernetes client
by using the `TryInto<Client> for kube_client::client::Config`. This
will construct a client with a Hyper `HttpConnector` which is
constructed by `kube-client`. In some cases, it may be desirable to
provide a custom HTTP client, such as when using an alternative TLS
implementation to those supported by `kube-client`.
This branch adds support for providing an alternative `tower::Service`
for the client used by  `kubert`'s `Runtime`. When using a custom client
`Service`, the Kubernetes client stack is still configured from the
provided `ClientArgs`, but the underlying HTTP connection is provided by
the user `Service`.
> client: Allow constructing client from a `Service`

- examples/Cargo.toml
- kubert/Cargo.toml
This will hopefully let us eliminate some mismatched Rustls versions.
> chore: bump `kube` deps to v0.84

- kubert/Cargo.toml
Compilation fails when the consumer of the kubert library has disabled all the default features and has enabled only the `lease` one.
The compilation fails because `lease.rs` uses `futures_util::TryFutureExt` but the `features-utils` library is not part of the dependencies.
> Fix compilation when only the `lease` feature is enabled

- kubert/src/runtime.rs
This is an internal change to consolidate Runtime type
construction.
> runtime: Remove server binding boilerplate

- deny.toml
- kubert/Cargo.toml
This branch updates the dependencies on `boring`, `tokio-boring`, and `hyper-boring` to v3.0.0. This dependency update does not appear to contain any breaking changes to the APIs currently used by Kubert, so the only reason this dependency bump had to be performed manually is because the `tokio-boring` and `hyper-boring` deps depend on `boring`, so the three crates must have their versions bumped atomically.
Because `boring-sys` v3.0 updates its dependency on `foreign-types` to the same major as `openssl-sys`, we no longer need to allow multiple versions of that crate in `deny.toml`.
Closes #174
Closes #175
Closes #176
> chore: update `boringssl` deps to v3.x

- examples/Cargo.toml
- kubert/Cargo.toml
This branch updates `kubert`'s dependencies on `kube-rs` to v0.85 and `k8s-openapi` to v0.19. This release of `k8s-openapi` adds support for Kubernetes v1.27.
I've also gone ahead and bumped `kubert`'s version to v0.18, since this is a breaking change.
> update to `kube-rs` v0.85 and `k8s-openapi` v0.19

- examples/Cargo.toml
- kubert/Cargo.toml
This commit temporarily pins the `clap` dependency version to v4.3.24, since v4.4 changed Clap's MSRV to Rust 1.70, which our dev image doesn't have yet. It was also necessary to add an explicit dep on `anstyle`, a transitive dep via `clap`, so that we could pin that crate to v1.0.0, as v1.0.1 of `anstyle` also requires Rust 1.70.
> temporarily pin `clap`  and `anstyle` dependencies

- .github/workflows/client.yml
- .github/workflows/lint.yml
- deny.toml
- examples/Cargo.toml
- examples/Dockerfile
- justfile
- kubert/Cargo.toml
- kubert/src/client.rs
- kubert/src/lib.rs
- kubert/src/runtime.rs
- kubert/src/server.rs
- kubert/src/server/tests.rs
- kubert/src/server/tls_openssl.rs
Depends on #190 
Currently, Kubert has the option to use either Rustls or BoringSSL as the TLS implementation. However, the BoringSSL feature is incomplete, as it only configures Kubert's server to use BoringSSL, while the client will still use "whatever `kube-client` is configured to use". This means that you don't *really* get all-BoringSSL. Meanwhile, using BoringSSL on the client-side is quite fraught without upstream support in `kube-client`.
Therefore, this branch rips out the `boring-tls` feature and replaces it with an `openssl-tls` feature. Now, we can ensure that the client and server use the same TLS implementation, because `kube-client` already supports OpenSSL. In addition, I've added new tests for the TLS server, and changed the CI client tests to run with both TLS clients. …
> replace BoringSSL with OpenSSL

- .github/workflows/client.yml
- .github/workflows/features.yml
- .github/workflows/lint.yml
- .github/workflows/release-prometheus-process.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Cargo.toml
- README.md
- deny.toml
- examples/Cargo.toml
- examples/watch_pods.rs
- kubert-prometheus-process/Cargo.toml
- kubert-prometheus-process/src/lib.rs
- kubert/Cargo.toml
- kubert/src/admin.rs
- kubert/src/admin/metrics.rs
This change replaces the `metrics` feature with a `prometheus-client` feature. prometheus-client is the official Prometheus-org OpenMetrics implementation.
The watch-pods example has been updated to export prometheus metrics:
:; curl localhost:8080/metrics
watch_pods_events_total{op="apply"} 0
watch_pods_events_total{op="delete"} 0
watch_pods_events_total{op="restart"} 1
watch_pods_current_pods 10
watch_pods_pods_total 10
process_start_time_seconds 1702159727.213669
process_uptime_seconds_total 2.712104395
process_cpu_seconds_total 0.73
process_virtual_memory_bytes 1208897536
process_resident_memory_bytes 21114880
process_open_fds 16
process_max_fds 1048576
process_threads 18
Furthermore, `admin::Builder` APIs are updated to consume the builder and return it by-value (instead of handling …
> admin: Replace 'metrics' with 'prometheus-client'

- .github/workflows/release-prometheus-process.yml
- .github/workflows/release.yml
- README.md
- kubert/Cargo.toml
* ci: Configure release name
* README improvement
> Prepare kubert v0.21.0

- examples/lease.rs
- examples/watch_pods.rs
The lease example now exports the lease state as a metric:
kubert_lease_claimed 1
kubert_lease_claim_changes_total 1
kubert_lease_claimed 0
kubert_lease_claim_changes_total 2
> examples: Update lease to export metrics

- .github/workflows/release.yml
Now tags use a kubert/ prefix instead of release/
> Update kubert release tag format

- .devcontainer/devcontainer.json
- .github/workflows/client.yml
- .github/workflows/features.yml
- .github/workflows/lint.yml
- .github/workflows/release-prometheus-process.yml
- .github/workflows/release-prometheus-tokio.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- examples/Cargo.toml
- examples/Dockerfile
- kubert-prometheus-process/Cargo.toml
- kubert-prometheus-tokio/Cargo.toml
- kubert/Cargo.toml
Update dev to v43, with Rust v1.76.
Adds rust-cache to workflows that fetch dependencies.
> Update MSRV to v74

- .github/workflows/features.yml
- examples/watch_pods.rs
- kubert/src/lib.rs
- kubert/src/runtime.rs
- kubert/src/runtime/metrics.rs
We add a `with_metrics` method to the kubert runtime builder which causes the runtime to create counters for resource watch events.  This is only available if the "prometheus-client" feature is enabled.
```
kubert_resource_watch_applies_total{kind="Pod",group="",version="v1"} 45
kubert_resource_watch_applies_total{kind="HTTPRoute",group="gateway.networking.k8s.io",version="v1beta1"} 376
kubert_resource_watch_applies_total{kind="Service",group="",version="v1"} 3
kubert_resource_watch_restarts_total{kind="HTTPRoute",group="policy.linkerd.io",version="v1beta3"} 1
kubert_resource_watch_restarts_total{kind="ExternalWorkload",group="workload.linkerd.io",version="v1beta1"} 1
kubert_resource_watch_restarts_total{kind="ServerAuthorization",group="policy.linkerd.io",version="v1beta1"} 1 …
```
> Add prometheus metrics for resource watch events

- kubert-prometheus-tokio/src/lib.rs
i noticed a sentence fragment while paging through the `kubert-prometheus-tokio` crate. this commit fixes that.
> 📝 chore: fix typo in `rt::Runtime` doc comment

- kubert-prometheus-tokio/Cargo.toml
- kubert/Cargo.toml
- kubert/src/initialized.rs
this branch contains two small patches, to facilitate building this project
with the current stable Rust toolchain.
building `kubert` with Rust 1.80 or later will fail, with an error
shaped like this:
```text
error: unexpected `cfg` condition name: `tokio_unstable`
--> kubert-prometheus-tokio/src/lib.rs:13:27
|
13 | #[cfg(all(feature = "rt", tokio_unstable))]
|                           ^^^^^^^^^^^^^^
|
= help: consider using a Cargo feature instead
= help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
= help: or consider adding `println!("cargo::rustc-check-cfg=cfg(tokio_unstable)");` to the top of the `build.rs`
= note: see …
```
> 🦀 chore: fix build errors for 1.80 toolchain

- kubert-prometheus-process/src/lib.rs
Upstream port from https://github.com/linkerd/linkerd2-proxy/pull/3176
> Add wall clock process metric

- deny.toml
- kubert/Cargo.toml
This release changes the lease::Error type to include a timeout variant.
> chore(kubert): v0.22.0

- .devcontainer/devcontainer.json
- .github/workflows/client.yml
- .github/workflows/features.yml
- .github/workflows/lint.yml
- .github/workflows/release-prometheus-process.yml
- .github/workflows/release-prometheus-tokio.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- deny.toml
- examples/Dockerfile
- kubert/src/admin/metrics.rs
- kubert/src/server.rs
* docker.io/library/golang from 1.22 to 1.23
* gotestsum from 0.4.2 to 1.12.0
* protoc-gen-go from 1.28.1 to 1.35.2
* protoc-gen-go-grpc from 1.2 to 1.5.1
* docker.io/library/rust from 1.76.0 to 1.83.0
* cargo-deny from 0.14.11 to 0.16.3
* cargo-nextest from 0.9.67 to 0.9.85
* cargo-tarpaulin from 0.27.3 to 0.31.3
* just from 1.24.0 to 1.37.0
* yq from 4.33.3 to 4.44.5
* markdownlint-cli2 from 0.10.0 to 0.15.0
* shellcheck from 0.9.0 to 0.10.0
* actionlint from 1.6.26 to 1.7.4
* protoc from 3.20.3 to 29.0
* step from 0.25.2 to 0.28.2
* kubectl from 1.29.2 to 1.31.3
* k3d from 5.6.0 to 5.7.5
* k3s image shas
* helm from 3.14.1 to 3.16.3
* helm-docs from 1.12.0 to 1.14.2
> build(deps): bump linkerd/dev from v43 to v44

- Cargo.toml
- deny.toml
- examples/Cargo.toml
- kubert-prometheus-process/Cargo.toml
- kubert-prometheus-tokio/Cargo.toml
- kubert/Cargo.toml
To make it easier to manage dependencies across the workspace, this changes moves the core dependencies to the workspace level.
> chore(cargo): move core/public dependencies to workspace

- Cargo.toml
- deny.toml
- examples/watch_pods.rs
- kubert/Cargo.toml
- kubert/src/index.rs
- kubert/src/runtime/metrics.rs
New versions of kube require k8s-openapi v0.23.
The kubert index implementation has been updated to use the new watcher API.
> build(deps): update kube to 0.97.0

- examples/Dockerfile
There's some build flakiness where the build step fails because of the --frozen flag. This is unexpected because we have previously fetched the dependencies.
To avoid these failures, this change removes the --frozen flag from the build.
> ci(examples): avoid flakiness by removing --frozen

- kubert/src/admin.rs
The admin server incorrectly instruments a blocking server. This change fixes the admin server to start in non-blocking mode. This prevents unexpected blocking.
> fix(admin): Set SOCK_NONBLOCK on the listener

- kubert/src/admin.rs
- kubert/src/server.rs
* Configure TCP_NODELAY for HTTP server sockets.
* Ensure the Hyper server is configured with a tokio timer.
> fix(admin,server): Fix HTTP server options

- examples/Cargo.toml
- kubert/Cargo.toml
- kubert/src/admin.rs
- kubert/src/admin/metrics.rs
- kubert/src/server.rs
This change introduces support for brotli and gzip compression via the following features:
- admin-brotli
- admin-gzip
- client-brotli
- client-gzip
- server-brotli
- server-gzip
Additionally, convenience features have been added to enable both brotli and gzip compression on all HTTP endpoints:
- admin-compression
- client-decompression
- server-compression
And convenience features have been added to enable compression for the client and admin runtime:
- runtime-brotli
- runtime-gzip
- runtime-compression
BREAKING CHANGE: The 'gzip' feature has been removed.
> feat(admin)!: support compression on all HTTP endpoints

- kubert/src/admin.rs
- kubert/src/admin/metrics.rs
Before expanding the admin functionality with diagnostics, this change cleans up some of the type signatures. No functional changes.
> chore(admin): cleanup admin router

- .github/workflows/pr.yml
- kubert/Cargo.toml
- kubert/src/admin.rs
- kubert/src/admin/diagnostics.rs
- kubert/src/admin/metrics.rs
- kubert/src/lib.rs
This change adds a new /kubert.json endpoint on the admin HTTP server. This endpoint returns a JSON object with various diagnostic information about the kubert runtime that do not readily fit into metrics. This admin endpoint is only available from the localhost and cannot be accessed from the non-loopback network.
The initial version of this endpoint includes only timestamp information. Additional diagnostic information will be added in future commits.
> feat(admin): add optional diagnostics endpoint

- .github/workflows/pr.yml
- examples/lease.rs
- kubert/src/lease.rs
- kubert/src/lib.rs
- kubert/src/runtime.rs
Lease initialization is currently decoupled from the runtime, which makes it difficult to instrument diagnostics automatically.
In preparation for lease diagnostics, this change adds a new `Runtime::spawn_lease` method that configures a managed lease.
> feat(runtime): add Runtime::spawn_lease

- kubert/src/admin/diagnostics.rs
- kubert/src/admin/diagnostics/watch.rs
To be generally consistent with kubernetes, this change makes the diagnostics endpoint emit json with camelCase keys.
> feat(diagnostics)!: use camelCase in returned json

- examples/Cargo.toml
- kubert/Cargo.toml
We have begun to use dep: features in our Cargo.toml files, but use is inconsistent which leads to friction. This commit updates all features to reference optional dependencies correctly.
> chore: update cargo.toml to use dep: features

- kubert/src/server.rs
- kubert/src/server/tests.rs
- kubert/src/server/tls_openssl.rs
- kubert/src/server/tls_rustls.rs
Both kube and kubert allow the rustls-tls and openssl-tls features simultaneously. However, their default behaviors differ, which causes clients and servers to use different TLS implementations when both features are enabled:
* kube clients use rustls-tls by default;
* kubert servers use openssl-tls by default.
This commit changes the default behavior of kubert servers to use rustls-tls when both features are enabled, aligning with [kube].
[kube]: https://github.com/kube-rs/kube/blob/6a980c6ea50f2f3f4f2867d3df3fd77be00fca84/kube-client/src/client/builder.rs#L157-L165
> feat(server): default to using rustls-tls

- .github/workflows/pr.yml
There's no need to test multiple TLS implementations on multiple Kubernetes versions. This change simplifies CI by excluding openssl on the minimum kubernetes version.
> ci: skip redundant MSKV tests

- kubert/src/client.rs
- kubert/src/runtime.rs
To prepare to instrument Kubernetes clients, this change introduces a basic ClientBuilder type.
> chore(client): introduce a ClientBuilder

- kubert/Cargo.toml
- kubert/src/client.rs
- kubert/src/client/timeouts.rs
The underlying kube client does not enforce any request timeouts, relying on the server to implement them. But this means that calls--especially those dispatched by a watcher--may hang indefinitely waiting for an API server response.
This change introduces a default timeout for response headers, which is set to 10s. Furthermore, the ClientArgs type is used to expose this timeout configuration as a command-line option, kube-api-response-headers-timeout.
> feat(client): add a default response headers timeout

- kubert/Cargo.toml
- kubert/src/client/metrics.rs
The prior change made it difficult to compare sent requests and received responses. This change introduces a new metric, response_status, that counts the number of responses received by status code.
> feat(client): add response_status counter

- .github/workflows/pr.yml
cargo-deny-action is broken: EmbarkStudios/cargo-deny-action#91
This change replaces the action with a manual invocation via the dev container image.
> fix(ci): remove EmbarkStudios/cargo-deny-action

- kubert-prometheus-process/Cargo.toml
- kubert-prometheus-tokio/Cargo.toml
- kubert/Cargo.toml
Drop alpha versions from kubert-prometheus-process, kubert-prometheus-tokio. Bump kubert to v0.23.1.
> chore: bump versions

- kubert-prometheus-process/src/linux.rs
- kubert-prometheus-process/src/linux/netstat.rs
Go prometheus export includes metrics like:
process_network_receive_bytes_total 2.68535043e+08
process_network_transmit_bytes_total 2.70816939e+08
This change ports their netstat parser to Rust so that we replicate the same metrics.
> feat(process): add receive_bytes and transmit_bytes
